name: deploy

on: [push]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"
      - name: Install Dependencies
        run: npm
      - name: Build
        run: |
            npm install
            npm install -g firebase-tools
      - name: deploy to Firebase Hosting
        run: |
            firebase deploy --token $FIREBASE_TOKEN --only hosting,firestore
        env:
            FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}